### ISSUE TITLE
mpd_run_status failing  in try_first() function called during shuffle_idle() 

### ISSUE THREAD

**Issue by franz159** [joshkunz/ashuffle#10]
**Issue Description**
The following code fragment in **ashuffle.c** is failing for me (the fprintf on stderr have been obviously added by me for debug reason)

```
int try_first(struct mpd_connection * mpd, struct shuffle_chain * songs) {
    struct mpd_status * status;
fprintf(stderr, "before mpd run status 1...\n");
    status = mpd_run_status(mpd);
fprintf(stderr, "after mpd run status 2...\n");
    if (status == NULL) {
        fprintf(stderr, "STATUS IS NULL!!!...\n");
        puts(mpd_connection_get_error_message(mpd));
        return -1;
    }
```
**Example error returned:**
> before mpd run status 1...
> after mpd run status 2...
> STATUS IS NULL!!!...
> Connection closed by the server

**Other info**
```
pi@moode4b4:~ $ mpc version
mpd version: 0.20.0
```
Number of tracks in MPD library: 43291

**Comment by joshkunz** [comment]
What version of libmpdclient are you running by chance?

**Comment by joshkunz** [comment]
Also, if you could post your mpd.log that would be super-great.

**Comment by franz159** [comment]
./usr/lib/*libmpd*client.so.2.0.9


mpd log in attachment


Regards

Franz

2017-10-02 9:24 GMT+02:00 Josh Kunz <notifications@github.com>:

**Comment by joshkunz** [comment]
Thanks, I'll start looking into it. Your attachment didn't get included in the issue, I think github just filtered it.

**Comment by franz159** [comment]
Any other email I can use to send the mpd.log in attachment?

Franz

2017-10-03 5:31 GMT+02:00 Josh Kunz <notifications@github.com>:

**Comment by joshkunz** [comment]
Sorry, I've been busy. You can email it to josh@kunz.xyz

**Comment by joshkunz** [comment]
I definitely no longer have this email if I ever received it. I'm going to declare bug clemency on this one. Please re-open if you'd like me to take a look at it.
