### ISSUE TITLE
Auto-Shuffle needs to be modified imho...

### ISSUE THREAD

**Issue by JST1963** [joshkunz/ashuffle#11]
Hi,
I'm a big fan of Tim Curtis' moOde software but there is something I really don't like. I explained him the problem but he said I had to contact you because you are the developer of this feature.
I'm still struggling with your feature "Auto-shuffle". Don't get me wrong, it works without hickups.
But I don't like the fact that the whole library of moOde is taken into account. I want to limit to certain parts of my library.
Let me explain: I'm using moOde at home, but also at work. And at home I don't really care what plays. But since I have the same library at the office, I want to select certain parts to choose from in the auto shuffle.
I have "normal" rock in my library, but also pop, metal, heavy metal, punk, funk, disco...actually a bit of everything, even classical music. And also some live albums.
Now, everything is well organized in different categories, folders and so on, all with year, genre, cover art....
So the problem now is, that at the office I'm not allowed to play for instance Rammstein, or even Metallica. Classical music is also not appreciated (dunno why, but hey...).
What I want is, since everything is well categorized, is to activate auto-shuffle, and in that window select the folders that I want into this auto-shuffle feature.
I really believe you should think about this. The feature Auto-Shuffle as it is now, is really useless at the office, because I constantly need skipping numbers.
What do you think? Please let me know asap...
Thx for your time!
Johan

**Comment by brainpower** [comment]
Have you considered using `--exclude` ?
Seems to me like adding `--exclude artist Rammstein --exclude artist Metallica --exclude genre Classical` to the ashuffle call would do what you want...

Exclude patterns are explained here: https://github.com/joshkunz/ashuffle#patterns

**Comment by joshkunz** [comment]
Thanks @brainpower! Yeah, I think the `--file` option, or exclude rules is the way to go here. I didn't develop the MoOde(sp?) integration with ashuffle, so I don't really control the UI. You'll have to ask them to add support for `--exclude` or `--file`.
