### ISSUE TITLE
Autoshuffle vs. Crossfade

### ISSUE THREAD

**Issue by audiofreak** [joshkunz/ashuffle#12]
Hi,

I really like auto-shuffle with my mo0de audioplayer (raspi 3 + allo boss).
But it seems that the mpd crossfade feature dosn't collaborate well with ashuffle.

Is there an easy way to tell ashuffle to add a new song to the playlist, as soon as the second to last song has already finished (and not the last one)? Than there would constantly be one file left as a "buffer" in the playlist and in this case I think that the crossfade would work fine.

That would be a killer feature for those like me who like three things:

- shuffle playback
- crossfade
- really big playlists

Thank you very much.

**Comment by joshkunz** [comment]
This is a very good point. I've added the `--queue_buffer` option which will make ashuffle keep a configurable buffer of songs at the end of the queue. You can pass `--queue_buffer 1` to keep 1 song in the queue after the currently playing song. Please re-open if this doesn't work for you.
