### ISSUE TITLE
Recent ARM binaries are actually x86-64

### ISSUE THREAD

**Issue by TheOldPresbyope** [joshkunz/ashuffle#122]
Up to v3.12.3 the ARM binaries such as ashuffle.armv6h-linux-gnueabihf are indeed ARM binaries, e.g.

```
pi@rpi3:~/tempdir/3.12.3 $ wget https://github.com/joshkunz/ashuffle/releases/download/v3.12.3/ashuffle.armv6h-linux-gnueabihf

pi@rpi3:~/tempdir/3.12.3 $ file ashuffle.armv6h-linux-gnueabihf
ashuffle.armv6h-linux-gnueabihf: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[xxHash]=091e97653de16f1e, with debug_info, not stripped

### ETA - what version is this 3.12.3 binary really ;-)
pi@rpi3:~/tempdir/3.12.3 $ chmod +x ashuffle.armv6h-linux-gnueabihf
pi@rpi3:~/tempdir/3.12.3 $ file ashuffle.armv6h-linux-gnueabihf -v
ashuffle version: v3.11.1
```
Beginning with V3.12.5 and up to current v3.13.0 they are x86-64, e.g.

```
pi@rpi3:~/tempdir/3.13.0 $ wget https://github.com/joshkunz/ashuffle/releases/download/v3.13.0/ashuffle.armv6h-linux-gnueabihf

pi@rpi3:~/tempdir/3.13.0 $ file ashuffle.armv6h-linux-gnueabihf
ashuffle.armv6h-linux-gnueabihf: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[xxHash]=aa33440ddc0d4e3f, with debug_info, not stripped
```

**Comment by joshkunz** [comment]
Ouch. Yeah that's definitely not supposed to happen.

**Comment by joshkunz** [comment]
I cannot repro this with meta directly. So thankfully this is probably a CI problem.

**Comment by joshkunz** [comment]
Should be fixed in v3.13.2

**Comment by TheOldPresbyope** [comment]
Confirmed that ashuffle.armv6h-linux-gnueabihf and ashuffle.armv7h-linux-gnueabihf binaries are what their names claim. Thanks!

**Comment by joshkunz** [comment]
FWIW, I’ve also added [basic checks](https://github.com/joshkunz/ashuffle/commit/2d4c1a7d11ce0ca7fe8da8385c6b1367de4abae1) to prevent this from regressing this bad again. Ideally I could test on each arch, but that requires spinning up custom runners.

Thanks for double-checking the build is correct.
