### ISSUE TITLE
Building on FreeBSD 11.2: An experience

### ISSUE THREAD

**Issue by purrloftruth** [joshkunz/ashuffle#18]
I was having some trouble building ashuffle on FreeBSD 11.2. I confirmed that I have libmpdclient installed and its .h files are available on the system. For some reason, though, I think that maybe they're not getting passed to CC?

```
[freebsd@icecast-source ~/ashuffle]$ make
 CC ashuffle
ashuffle.c:2:10: fatal error: 'mpd/client.h' file not found
#include <mpd/client.h>
         ^~~~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make[1]: stopped in /usr/home/freebsd/ashuffle/src
*** Error code 1

Stop.
make: stopped in /usr/home/freebsd/ashuffle
```

Running `make -d A` reveals that the actual command being run is `cc '-std=c99' -Wall -Wextra -pedantic ashuffle.c -o ashuffle`, which doesn't look like it's being passed any of the libraries.

Then I tried running `gmake` instead, which worked:

```
[freebsd@icecast-source ~/ashuffle]$ gmake
gmake[1]: Entering directory '/usr/home/freebsd/ashuffle/src'
 CC ashuffle.o
 CC args.o
 CC rule.o
 CC shuffle.o
 CC list.o
 CC getpass.o
 CC ashuffle
gmake[1]: Leaving directory '/usr/home/freebsd/ashuffle/src'
 COPY ./src/ashuffle .
[freebsd@icecast-source ~/ashuffle]$
```

But when I went to `make install`, I ran into another issue:

```
[freebsd@icecast-source ~/ashuffle]$ sudo gmake install
gmake[1]: Entering directory '/usr/home/freebsd/ashuffle/src'
gmake[1]: 'ashuffle' is up to date.
gmake[1]: Leaving directory '/usr/home/freebsd/ashuffle/src'
 COPY ./src/ashuffle .
install -t /usr/local/bin ashuffle
install: illegal option -- t
usage: install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               [-B suffix] [-l linkflags] [-N dbdir]
               file1 file2
       install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               [-B suffix] [-l linkflags] [-N dbdir]
               file1 ... fileN directory
       install -dU [-vU] [-g group] [-m mode] [-N dbdir] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               directory ...
gmake: *** [Makefile:18: install] Error 64
```

I had to modify this part of the main Makefile to adjust to how install seems to work on FreeBSD:

```
install: $(BIN)
        install $(BIN) $(prefix)/bin/$(BIN)
```

This got it to work:

```
[freebsd@icecast-source ~/ashuffle]$ sudo gmake install
gmake[1]: Entering directory '/usr/home/freebsd/ashuffle/src'
gmake[1]: 'ashuffle' is up to date.
gmake[1]: Leaving directory '/usr/home/freebsd/ashuffle/src'
 COPY ./src/ashuffle .
install ashuffle /usr/local/bin/ashuffle
[freebsd@icecast-source ~/ashuffle]$
```

It would be nice if future revisions of ashuffle were ready for FreeBSD out of the box. Thanks again for all your hard work on this piece of software!!!

**Comment by joshkunz** [comment]
> Running make -d A reveals that the actual command being run is cc '-std=c99' -Wall -Wextra -pedantic ashuffle.c -o ashuffle, which doesn't look like it's being passed any of the libraries.

`ashuffle` uses [`pkg-config` and the `$(shell)` make function](
https://github.com/joshkunz/ashuffle/blob/master/src/Makefile#L11) to fetch the appropriate flags for compilation and linking. It seems like the `$(shell)` function might only be supported by gmake. If that’s the case, then `ashuffle` would need to add its own C build rule that supports `pkg-config` or switch build systems (maybe to `meson`? That’s what MPD and libmpdclient are using).

I’m open pull requests if you’d like to attempt this. I’ll probably get around to it eventually. 😉

> But when I went to make install, I ran into another issue...

This is a pretty simple change, I’ve already changed this at HEAD (not in a tagged release yet).

> Thanks again for all your hard work on this piece of software!!!

You’re welcome :smile:. I’m glad people find it useful.

**Comment by joshkunz** [comment]
Thanks to #20, ashuffle now has a meson build file. I think that addresses the platform-related issues you had, so I’m going to close this. Please re-open if you see any remaining gaps.
