### ISSUE TITLE
Trying to play a file with an empty queue doesn't work

### ISSUE THREAD

**Issue by Joshkunz** [Joshkunz/ashuffle#2]
Likely caused by a race with the player.

Steps to reproduce:

1. Start `ashuffle`
3. run `mpc clear`. At this point the music stops. (should ashuffle add another song here?)
2. run `mpc add <song-file>`. At this point, ashuffle will queue another song and begin playing it instead of the song we just added.

**Comment by brainpower** [comment]
Is this the reason why it won't work when in consume-mode or is that a different issue?

**Comment by Joshkunz** [comment]
@brainpower no, I think that's a different issue. With this particular bug, trying to add a song to the queue will cause ashuffle to queue up another song (after the just-added song) and play it, effectively 'skipping' the first song.

I've opened another issue #3 for the consume mode bug.

**Comment by Joshkunz** [comment]
Should be fixed on master branch.
