### ISSUE TITLE
Arguments parsing using strtoul incorrectly giving errors

### ISSUE THREAD

**Issue by martinetd** [joshkunz/ashuffle#23]
I'm not sure if this is arch/build/environment dependent but I can sometimes get `shuffle --queue_buffer 1` to complain it could not convert queue_buffer's argument (it happened for me when building with `meson -Db_sanitize=address` on arm7l linux gnu)

The reason for this is that `strotul` does not reset errno to 0 if there is no error, so the current way of checking errno only works if it wasn't EINVAL or ERANGE before.
There are multiple ways of solving this, for example reseting `errno` before calling strtoul should work in principle, but that won't complain if the user passes something that starts with digits e.g. `--queue_buffer 42waswrong` will not error.
The "correct" way of checking for strtoul success is to pass a endptr argument and check that it points to a nul byte; anything else and the string was not fully parsed.

(While looking at this, I also noticed we're not checking that there are enough arguments, e.g. `ashuffle --queue_buffer` does not error out either; it probably should)

Likewise, happy to submit a PR, but it's likely just as fast to fix directly - your call. Sorry for the "spam" :)

**Comment by joshkunz** [comment]
Yeah, that sounds like a bug. I always appreciate PRs if you’re willing 😄 Otherwise, I’m sure I’ll get around to patching this eventually.

> Sorry for the "spam" :)

No worries at all, totally valid bug. There’s plenty of these types of fixes that need to be done. I think increased reliability is the next “big” feature for ashuffle.

**Comment by martinetd** [comment]
Okay, will whip something up over the weekend then, it's not too much work.
