### ISSUE TITLE
add ability to send extra command when adding new song to playlist

### ISSUE THREAD

**Issue by Atreus-Tantalus** [joshkunz/ashuffle#25]
For example i would send command to my i3bar to refresh current_song widget.

**Comment by joshkunz** [comment]
This seems like it could be accomplished by a different MPD client. I don't think there's a compelling reason `ashuffle` should provide this functionalty.

For example, if you wanted to update your status bar when playlist/player status changes you could use a small bash script + [MPC](https://www.musicpd.org/clients/mpc/) like so:

```bash
while mpc idle playlist player; do
  <command>
done
```

Closing. Feel free to re-open if you disagree.
