### ISSUE TITLE
Release Tarball fails to configure

### ISSUE THREAD

**Issue by brainpower** [joshkunz/ashuffle#37]
The meson.build file with default options includes the t/meson.build which searches for libtap/tap.c .
The latter is not included in githubs [release tarball], thus ashuffle fails to "configure" with the following error:

    t/meson.build:2:0: ERROR: File libtap/tap.c does not exist.

Steps to reproduce:
1. Go to github releases
2. Download "Source code (tar.gz)" from assets
3. Unpack, cd into it
4. run `meson build`
5. Observe above error

Workaround: Replace Step 4 with:  `meson build -Dtidy_mode=true` , but this disables tests...

[release tarball]: https://github.com/joshkunz/ashuffle/archive/v2.0.0.tar.gz

**Comment by joshkunz** [comment]
Thanks for the speedy bug-report!

This should be fixed by PR #38, which has been merged as`v2.0.1`. I've disabled tests by default, they can be enabled again with `-D=enabled` (as documented in `t/readme.md`).
