### ISSUE TITLE
Add testing for release build.

### ISSUE THREAD

**Issue by joshkunz** [joshkunz/ashuffle#39]
Specifically, test for being able to build without submodules. See issue #37.

**Comment by brainpower** [comment]
libtap does not seem to update very often, there's one release from 2015 and the newest commit was made in Dec 2018, so...
I'd suggest to just put a plain copy of it into your repo. Seems like the easiest and simplest solution.

Else you'd probably have to investigate if github can put submodules into release tarballs... or getting libtap some other way. (distribution's packages?)

**Comment by joshkunz** [comment]
I think it's fine for the release tarballs to not support testing, as long as the compilation instructions work. Anyone interested in ashuffle development can just clone the repo directly, and setup submodules.

**Comment by joshkunz** [comment]
As of `957e5b912b110ad4c5b8605884a918cc693d07c4`, ashuffle's travis build is doing a regular release build. Also, since we're releasing linux binaries now, I think this issue is semi-obsolete.
