### ISSUE TITLE
feature: "shuffle albums instead of songs" mode

### ISSUE THREAD

**Issue by scruloose** [joshkunz/ashuffle#43]
Hi there!  Seeing that you've been doing all this work on a music-shuffling program, would it be relatively easy to add a mode that, rather than playing songs picked at random, randomly picks an album from the library, plays the album straight through, and then moves on to another randomly selected album?

Personally I find that full shuffle is often too jarring, and I like listening to albums all the way through, but it would be *really* nice if I could get a program to just keep that stream of albums playing without me having to think about what to put on!  In case this does happen to interest you, I should point out that for usability, the full-album shuffle mode really needs to have simple ways both to skip the current song *and* to jump to another album immediately. (Sometimes you're just not in the mood for what the RNG picked.)

This is a feature I would have expected to be common in mainstream music players, but that hasn't been my experience.

**Comment by joshkunz** [comment]
Thanks for the feature request!

This seems to be in a similar spirit to issue #8 I filed a while back. This is something that should definitely be added. Album-based shuffle is not well-addressed by other MPD clients. I'm not sure when I'll have time to add support, but I'll get around to it eventually. If you'd like to take a shot at it, pull requests are always welcome :)

> I should point out that for usability, the full-album shuffle mode really needs to have simple ways both to skip the current song and to jump to another album immediately.

This is a good point, but I'm not sure it's feasible given the way MPD/ashuffle work. ashuffle just listens for player events (like skipping a song), and then reacts to them (adds a new song to the queue). There's no way for it to observe events that are not already part of MPDs player interface.

Unfortunately, I think this is best left to other (user-facing) clients to implement. It should be possible for a client to skip past all contiguous songs on the same album. Worst case users can hack something together using `mpc`. Once there are no songs left in the queue, ashuffle can react, and queue up the next album, just like how it works for individual songs.

**Comment by joshkunz** [comment]
@scruloose, if you're still interested in this feature and have the time, I'd love some feedback on PR #55. Does it work like you'd expect?

**Comment by ddffnn** [comment]
I've been looking for this too. I'm happy with how this PR is working, but I've only used the `--by-album` flag so far. I'll be sure to let you know if I see something I don't expect.

I'm really happy to have this feature though.

**Comment by joshkunz** [comment]
@ddffnn Thanks for the feedback! It's very good to know that the feature is working well. I think I'll merge it in the next couple days unless I get more feedback.

**Comment by joshkunz** [comment]
Finally got the tests figured out. Merged as `v3.3.0`.
