### ISSUE TITLE
getline issue

### ISSUE THREAD

**Issue by DerTFL** [Joshkunz/ashuffle#6]
Hello!

The problem is that getline() is a standard library function. (defined in stdio.h) Your function has the same name and is thus clashing with it.

The solution is to simply change the name.

Thanks!

**Comment by Joshkunz** [comment]
I didn't even realize I was already using `getline` in `ashufle.c`. I've updated ashuffle's `getpass` to use the standard getline. Thanks for the issue!

**Comment by DerTFL** [comment]
Thank you!
Now it works.
