### ISSUE TITLE
Would appreciate help packaging for Void Linux.

### ISSUE THREAD

**Issue by kartikynwa** [joshkunz/ashuffle#70]
Hi. Love this software. I use it everyday.

I am trying to package it for the Void Repos. I had to add `abseil-cpp` to the repos and update `gtest`. These two build fine but `ashuffle` runs into issues. This is the output:  http://dpaste.com/1YCK6XW

If you'd like to, you can look at the tentative templates for [`ashuffle`](https://github.com/kartikynwa/void-packages/blob/ashuffle/srcpkgs/ashuffle/template) and [`abseil-cpp`](https://github.com/kartikynwa/void-packages/blob/ashuffle/srcpkgs/abseil-cpp/template).

I don't know what this means so any input would be appreciated. Thank you.

---

### Edit

The previous problem seemed to be related to packaging `abseil-cpp` which I have managed to fix. But I get this error now: http://dpaste.com/02XRTS0

Looking at the source, looks like the function ends without returning but you assert that that situation would be unreachable.

Any advice on dealing with this would be appreciated. The links to the templates above have been updated. Thanks.

---

### Edit 2

For now I have worked around that problem by adding [a patch[(https://github.com/kartikynwa/void-packages/blob/ashuffle/srcpkgs/ashuffle/patches/fix-werror.patch) that replaces the assert statement with a "return invalid argument" statement. If you can think of more elegant solutions feel free to let me know.

**Comment by joshkunz** [comment]
@kartikynwa Sorry for the delayed response, I'm glad you figured the issue out!

Does PR #71 fix the error you mentioned in "Edit 1"? The `-Wreturn-type` error does not manifest on my end. That bit of code should be truly unreachable, so I'd rather just tell the compiler that.

Also, if you're publishing your void-linux package please open a PR adding a reference to the package to `readme.md`. If you'd rather not open a PR, I would appreciate getting the name of the package in whatever form a void-linux user would expect, so I can add it to the readme 😄 .

**Comment by kartikynwa** [comment]
That should fix it. Thanks a lot for the response.

If it gets accepted, I will file a PR for adding the package to the README.

Thanks again.
