### ISSUE TITLE
Add an option to disable automatic play

### ISSUE THREAD

**Issue by dos1** [joshkunz/ashuffle#72]
When starting ashuffle, it adds a random song to the playlist and immediately starts to play it. This makes my PC automatically start playing at each boot, since I have it configured to start mpd and ashuffle at boot as shuffling through library is how I usually use mpd.

It would be really great to be able to disable automatic playback at ashuffle's launch.

**Comment by joshkunz** [comment]
Makes sense. I agree we should add this. Only thing I'm a little concerned about is `ashuffle`'s CLI getting too complicated. This seems like it would probably be an infrequently used feature. I think we should hide this and similar options (e.g., #67) behind some standard flag for minor behavior tweaks. Maybe `--tweak` or something...

Either way, this will definitely be added.

**Comment by joshkunz** [comment]
Released as `--tweak play-on-startup=no` in `v3.7.0`. Let me know if this doesn't work as expected.
