### ISSUE TITLE
GROUP BY-like functionality

### ISSUE THREAD

**Issue by joshkunz** [joshkunz/ashuffle#8]
It would be nice if you could pass a flag to ashuffle like `--group album` and it would do something like shuffle the albums instead of the songs individually. I don't really know what the best way to expose this would be. 

Questions:

  * What kind of groups would you want to express? Albums? Artists? Maybe combinations like Artist + Year?
  * What does it mean to "shuffle a group". Do we play all the songs in that group? In what order?

**Comment by ibeex** [comment]
IMHO - Album and play it in songs order, then another album ...

**Comment by joshkunz** [comment]
See also #43.

**Comment by joshkunz** [comment]
Merged as `v3.3.0`.
